// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3szh6LP7dB4sla4WFZGxRmtES-Szlt3Q',
    appId: '1:1022095367959:web:51464e8c1e12feb53b2152',
    messagingSenderId: '1022095367959',
    projectId: 'nyuad-laundry',
    authDomain: 'nyuad-laundry.firebaseapp.com',
    storageBucket: 'nyuad-laundry.appspot.com',
    measurementId: 'G-RTTC1DJP7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg6_PVNx-WQvJ-J5q0WSWU9cwiNgxg4lw',
    appId: '1:1022095367959:android:8dae381d83384f363b2152',
    messagingSenderId: '1022095367959',
    projectId: 'nyuad-laundry',
    storageBucket: 'nyuad-laundry.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8RFa2zIvCYJmABDGoMe_Ab3b7F_5Kpmg',
    appId: '1:1022095367959:ios:f4d1792c7065be8e3b2152',
    messagingSenderId: '1022095367959',
    projectId: 'nyuad-laundry',
    storageBucket: 'nyuad-laundry.appspot.com',
    iosClientId: '1022095367959-lrdrr9hecn9296d8kfcqcjug6vj6t1tm.apps.googleusercontent.com',
    iosBundleId: 'com.example.laundry',
  );
}
